// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFfn3HYjWYwHbMOC3S8onYADEK_I2_Mmc',
    appId: '1:383515996407:web:fe18956cf4c947c7e223f2',
    messagingSenderId: '383515996407',
    projectId: 'smartlocker-2137e',
    authDomain: 'smartlocker-2137e.firebaseapp.com',
    storageBucket: 'smartlocker-2137e.firebasestorage.app',
    measurementId: 'G-1P3KL6SRL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBKIr2WC6_ApHvodxnyn3ti1AKrCbHuIw',
    appId: '1:383515996407:android:38aff63a1540fefde223f2',
    messagingSenderId: '383515996407',
    projectId: 'smartlocker-2137e',
    storageBucket: 'smartlocker-2137e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb85Qazg4LJnrGCpVMwUHDwixFuXgLzrM',
    appId: '1:383515996407:ios:f0aac1b516b7211fe223f2',
    messagingSenderId: '383515996407',
    projectId: 'smartlocker-2137e',
    storageBucket: 'smartlocker-2137e.firebasestorage.app',
    iosBundleId: 'com.example.smartlockersystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb85Qazg4LJnrGCpVMwUHDwixFuXgLzrM',
    appId: '1:383515996407:ios:f0aac1b516b7211fe223f2',
    messagingSenderId: '383515996407',
    projectId: 'smartlocker-2137e',
    storageBucket: 'smartlocker-2137e.firebasestorage.app',
    iosBundleId: 'com.example.smartlockersystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFfn3HYjWYwHbMOC3S8onYADEK_I2_Mmc',
    appId: '1:383515996407:web:5129bb3966209fdbe223f2',
    messagingSenderId: '383515996407',
    projectId: 'smartlocker-2137e',
    authDomain: 'smartlocker-2137e.firebaseapp.com',
    storageBucket: 'smartlocker-2137e.firebasestorage.app',
    measurementId: 'G-L34BH2DMGF',
  );
}
